@echo off

SET ILMERGE_VERSION=3.0.29

SET ILMERGE_PATH=%USERPROFILE%\.nuget\packages\ilmerge\%ILMERGE_VERSION%\tools\net452
echo Merging Blobber.exe...

"%ILMERGE_PATH%"\ILMerge.exe Blobber\Bin\Debug\Blobber.exe  ^
  /lib:Blobber\Bin\Debug\ ^
  /out:Blobber.exe ^
  Blobber\bin\Debug\Azure.Core.dll ^
  Blobber\bin\Debug\Azure.Storage.Blobs.dll ^
  Blobber\bin\Debug\Azure.Storage.Common.dll ^
  Blobber\bin\Debug\Microsoft.Bcl.AsyncInterfaces.dll ^
  Blobber\bin\Debug\Microsoft.Win32.Primitives.dll ^
  Blobber\bin\Debug\netstandard.dll ^
  Blobber\bin\Debug\System.AppContext.dll ^
  Blobber\bin\Debug\System.Buffers.dll ^
  Blobber\bin\Debug\System.Collections.Concurrent.dll ^
  Blobber\bin\Debug\System.Collections.dll ^
  Blobber\bin\Debug\System.Collections.NonGeneric.dll ^
  Blobber\bin\Debug\System.Collections.Specialized.dll ^
  Blobber\bin\Debug\System.ComponentModel.dll ^
  Blobber\bin\Debug\System.ComponentModel.EventBasedAsync.dll ^
  Blobber\bin\Debug\System.ComponentModel.Primitives.dll ^
  Blobber\bin\Debug\System.ComponentModel.TypeConverter.dll ^
  Blobber\bin\Debug\System.Console.dll ^
  Blobber\bin\Debug\System.Data.Common.dll ^
  Blobber\bin\Debug\System.Diagnostics.Contracts.dll ^
  Blobber\bin\Debug\System.Diagnostics.Debug.dll ^
  Blobber\bin\Debug\System.Diagnostics.DiagnosticSource.dll ^
  Blobber\bin\Debug\System.Diagnostics.FileVersionInfo.dll ^
  Blobber\bin\Debug\System.Diagnostics.Process.dll ^
  Blobber\bin\Debug\System.Diagnostics.StackTrace.dll ^
  Blobber\bin\Debug\System.Diagnostics.TextWriterTraceListener.dll ^
  Blobber\bin\Debug\System.Diagnostics.Tools.dll ^
  Blobber\bin\Debug\System.Diagnostics.TraceSource.dll ^
  Blobber\bin\Debug\System.Diagnostics.Tracing.dll ^
  Blobber\bin\Debug\System.Drawing.Primitives.dll ^
  Blobber\bin\Debug\System.Dynamic.Runtime.dll ^
  Blobber\bin\Debug\System.Globalization.Calendars.dll ^
  Blobber\bin\Debug\System.Globalization.dll ^
  Blobber\bin\Debug\System.Globalization.Extensions.dll ^
  Blobber\bin\Debug\System.IO.Compression.dll ^
  Blobber\bin\Debug\System.IO.Compression.ZipFile.dll ^
  Blobber\bin\Debug\System.IO.dll ^
  Blobber\bin\Debug\System.IO.FileSystem.dll ^
  Blobber\bin\Debug\System.IO.FileSystem.DriveInfo.dll ^
  Blobber\bin\Debug\System.IO.FileSystem.Primitives.dll ^
  Blobber\bin\Debug\System.IO.FileSystem.Watcher.dll ^
  Blobber\bin\Debug\System.IO.IsolatedStorage.dll ^
  Blobber\bin\Debug\System.IO.MemoryMappedFiles.dll ^
  Blobber\bin\Debug\System.IO.Pipes.dll ^
  Blobber\bin\Debug\System.IO.UnmanagedMemoryStream.dll ^
  Blobber\bin\Debug\System.Linq.dll ^
  Blobber\bin\Debug\System.Linq.Expressions.dll ^
  Blobber\bin\Debug\System.Linq.Parallel.dll ^
  Blobber\bin\Debug\System.Linq.Queryable.dll ^
  Blobber\bin\Debug\System.Memory.dll ^
  Blobber\bin\Debug\System.Net.Http.dll ^
  Blobber\bin\Debug\System.Net.NameResolution.dll ^
  Blobber\bin\Debug\System.Net.NetworkInformation.dll ^
  Blobber\bin\Debug\System.Net.Ping.dll ^
  Blobber\bin\Debug\System.Net.Primitives.dll ^
  Blobber\bin\Debug\System.Net.Requests.dll ^
  Blobber\bin\Debug\System.Net.Security.dll ^
  Blobber\bin\Debug\System.Net.Sockets.dll ^
  Blobber\bin\Debug\System.Net.WebHeaderCollection.dll ^
  Blobber\bin\Debug\System.Net.WebSockets.Client.dll ^
  Blobber\bin\Debug\System.Net.WebSockets.dll ^
  Blobber\bin\Debug\System.Numerics.Vectors.dll ^
  Blobber\bin\Debug\System.ObjectModel.dll ^
  Blobber\bin\Debug\System.Reflection.dll ^
  Blobber\bin\Debug\System.Reflection.Extensions.dll ^
  Blobber\bin\Debug\System.Reflection.Primitives.dll ^
  Blobber\bin\Debug\System.Resources.Reader.dll ^
  Blobber\bin\Debug\System.Resources.ResourceManager.dll ^
  Blobber\bin\Debug\System.Resources.Writer.dll ^
  Blobber\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll ^
  Blobber\bin\Debug\System.Runtime.CompilerServices.VisualC.dll ^
  Blobber\bin\Debug\System.Runtime.dll ^
  Blobber\bin\Debug\System.Runtime.Extensions.dll ^
  Blobber\bin\Debug\System.Runtime.Handles.dll ^
  Blobber\bin\Debug\System.Runtime.InteropServices.dll ^
  Blobber\bin\Debug\System.Runtime.InteropServices.RuntimeInformation.dll ^
  Blobber\bin\Debug\System.Runtime.Numerics.dll ^
  Blobber\bin\Debug\System.Runtime.Serialization.Formatters.dll ^
  Blobber\bin\Debug\System.Runtime.Serialization.Json.dll ^
  Blobber\bin\Debug\System.Runtime.Serialization.Primitives.dll ^
  Blobber\bin\Debug\System.Runtime.Serialization.Xml.dll ^
  Blobber\bin\Debug\System.Security.Claims.dll ^
  Blobber\bin\Debug\System.Security.Cryptography.Algorithms.dll ^
  Blobber\bin\Debug\System.Security.Cryptography.Csp.dll ^
  Blobber\bin\Debug\System.Security.Cryptography.Encoding.dll ^
  Blobber\bin\Debug\System.Security.Cryptography.Primitives.dll ^
  Blobber\bin\Debug\System.Security.Cryptography.X509Certificates.dll ^
  Blobber\bin\Debug\System.Security.Principal.dll ^
  Blobber\bin\Debug\System.Security.SecureString.dll ^
  Blobber\bin\Debug\System.Text.Encoding.dll ^
  Blobber\bin\Debug\System.Text.Encoding.Extensions.dll ^
  Blobber\bin\Debug\System.Text.RegularExpressions.dll ^
  Blobber\bin\Debug\System.Threading.dll ^
  Blobber\bin\Debug\System.Threading.Overlapped.dll ^
  Blobber\bin\Debug\System.Threading.Tasks.dll ^
  Blobber\bin\Debug\System.Threading.Tasks.Extensions.dll ^
  Blobber\bin\Debug\System.Threading.Tasks.Parallel.dll ^
  Blobber\bin\Debug\System.Threading.Thread.dll ^
  Blobber\bin\Debug\System.Threading.ThreadPool.dll ^
  Blobber\bin\Debug\System.Threading.Timer.dll ^
  Blobber\bin\Debug\System.ValueTuple.dll ^
  Blobber\bin\Debug\System.Xml.ReaderWriter.dll ^
  Blobber\bin\Debug\System.Xml.XDocument.dll ^
  Blobber\bin\Debug\System.Xml.XmlDocument.dll ^
  Blobber\bin\Debug\System.Xml.XmlSerializer.dll ^
  Blobber\bin\Debug\System.Xml.XPath.dll ^
  Blobber\bin\Debug\System.Xml.XPath.XDocument.dll 

dir %APP_NAME%
pause